# Generated by Django 5.0.2 on 2024-03-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0002_alter_rating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
