# Generated by Django 5.0.2 on 2024-03-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_movie_runtime_movie_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.CharField(max_length=15),
        ),
    ]
