# Generated by Django 5.0.2 on 2024-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_alter_movie_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
