# Generated by Django 4.2.11 on 2024-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0006_movie_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(),
        ),
    ]
